const nodemailer = require("nodemailer");

let transporter = null;
let emailEnabled = false;

function createTransporter() {

    try {

        transporter = nodemailer.createTransport({
            service: "gmail",
            auth: {
                user: process.env.EMAIL_USER,
                pass: process.env.EMAIL_PASS
            },
            connectionTimeout: 10000,
            greetingTimeout: 5000,
            socketTimeout: 10000
        });

        console.log("Email transporter created");
        return transporter;

    } catch (error) {

        console.error("Failed to create transporter:", error);
        return null;
    }
}

async function verifyEmailConnection() {

    if (!transporter) {
        createTransporter();
    }

    if (!transporter) {
        emailEnabled = false;
        return false;
    }

    try {

        await transporter.verify();

        emailEnabled = true;

        console.log("Email service verified successfully");

        return true;

    } catch (error) {

        emailEnabled = false;

        console.error("Email verification failed:");
        console.error(error.message);

        return false;
    }
}

async function sendRecommendationEmail(
    name,
    email,
    recommendation,
    reason
) {

    if (!emailEnabled) {

        console.warn(
            "Email service unavailable. Skipping email."
        );

        return null;
    }

    try {

        console.log("Sending email to:", email);

        const info =
        await transporter.sendMail({

            from: process.env.EMAIL_USER,

            to: email,

            subject:
            "Academic Pathway Recommendation",

            html: `
                <div style="font-family: Arial, sans-serif; padding:20px;">

                    <h2>Academic Pathway Recommendation</h2>

                    <p>Hello <strong>${name}</strong>,</p>

                    <p>Your recommendation has been generated.</p>

                    <h3>${recommendation}</h3>

                    <p>${reason}</p>

                    <hr>

                    <small>
                        Generated by Academic Pathway Recommendation Engine
                    </small>

                </div>
            `
        });

        console.log(
            "Email sent successfully:",
            info.messageId
        );

        return info;

    } catch (error) {

        console.error("Email send failed:");
        console.error(error.message);

        return null;
    }
}

function sendRecommendationEmailNonBlocking(
    name,
    email,
    recommendation,
    reason
) {

    sendRecommendationEmail(
        name,
        email,
        recommendation,
        reason
    ).catch(error => {

        console.error(
            "Background email failed:",
            error.message
        );

    });
}

module.exports = {
    createTransporter,
    verifyEmailConnection,
    sendRecommendationEmail,
    sendRecommendationEmailNonBlocking
};